apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: postgres-operator
  namespace: demo
spec:
  containers:
  - name: psql-container
    image: postgres
    command: ['sh', '-c', 'sleep 3600']
    env:
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: mycluster-postgres-secret
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: mycluster-postgres-secret
          key: password
  initContainers:
  - name: init-pgo
    image: quay.io/guineveresaenger/guinstest:latest
    imagePullPolicy: Always
    env:
    - name: CO_APISERVER_URL
      value: https://postgres-operator.demo.svc.cluster.local:8443
    - name: PGOUSER
      value: username
    - name: PGO_CA_CERT
      value: /conf/apiserver/server.crt
    - name: PGO_CLIENT_CERT
      value: /conf/apiserver/server.crt
    - name: PGO_CLIENT_KEY
      value: /conf/apiserver/server.key

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgo-backup
            image: quay.io/guineveresaenger/guinstest:latest
            command: ['sh', '-c', 'echo username:password > ~/.pgouser && echo backing up: && pgo backup mycluster']
            env:
            - name: CO_APISERVER_URL
              value: https://postgres-operator.demo.svc.cluster.local:8443
            - name: PGOUSER
              value: username
            - name: PGO_CA_CERT
              value: /conf/apiserver/server.crt
            - name: PGO_CLIENT_CERT
              value: /conf/apiserver/server.crt
            - name: PGO_CLIENT_KEY
              value: /conf/apiserver/server.key
          restartPolicy: OnFailure

